use_frameworks!

target 'SKTitleScrollNavigaionView_Example' do
  pod 'SKTitleScrollNavigaionView', :path => '../'

  target 'SKTitleScrollNavigaionView_Tests' do
    inherit! :search_paths

    
  end
end
